name: PluginDisabler
version: '${project.version}'
main: net.twistpvp.plugindisabler.PluginDisabler
api-version: 1.16
permissions:
  pluginhider.admin:
    description: Allows admins to bypass the filter
commands:
  pluginhider:
    aliases:
      - ph
